all:
  hosts:
    server-139:
      ansible_ssh_host: 139.59.67.104
      ansible_ssh_user: nischal
    server-167:
      ansible_ssh_host: 167.71.229.214
      ansible_ssh_user: nischal
    sakchyam:
      ansible_ssh_private_key_file: /home/nischal/.ssh/cibot_naxa.pem
      ansible_ssh_user: ubuntu
      ansible_ssh_host: 65.0.145.137
    new_server:
      ansible_ssh_user: ubuntu
      ansible_ssh_host: 103.90.84.31
