- name: Testing Ansible
  hosts: all #targets webservers group on /etc/ansible/hosts
  # remote_user: root

  tasks:
  - name: Jenkins Backup
    # become: true 
    copy:
      src: ~/naxa/ansible/node-exporter/
      dest: ~/node-exporter

  - name: Creating a Jenkins backup script
    copy:
    dest: "~/ansible-scripts/"
    content: |
    mkdir ~/jenkins_backup_script/
    FOLDER_NAME=JENKINS-$(date +"%d-%m-%Y")
    mkdir $FOLDER_NAME
    rsync -av --progress /var/lib/jenkins/* /home/nischal/jenkins_backup/$FOLDER_NAME --exclude workspace --exclude .npm
    tar -cvzf $FOLDER_NAME.tar.gz $FOLDER_NAME
    rm -rf $FOLDER_NAME
    find /home/nischal/jenkins_backup/* -type f -ctime +7 -exec rm -rf {} \;
  - name: Create Docker Container For Node Exporter
    # become: true 
    command: "cd ~/node-exporter"
    command: "docker-compose up -d"
  # - name: DOCker PS
  #   command: "touch ansible_created_file.txt"
    