- name: Add SSH Key
  hosts: remote-server
  become: yes
  vars:
    - user: new_demo_user

  tasks:
  - name: Add public key to authorized_keys
    authorized_key:
      user: "{{ user }}"
      state: present
      key: '{{ item }}'
    # key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    with_file:
    - ~/.ssh/id_rsa.pub

  # - name: "get the file content"
  #   slurp:
  #     src: "/etc/ssh/sshd_config"
  #   register: file

  # - name: "fetch the right line"
  #   set_fact:
  #     line: "{{ file['content'] | b64decode | regex_search('AllowUsers.*')}}"

  # - name: "extract the users"
  #   set_fact:
  #     allowed_users: "{{ line.split()[1:-1] }}"

  # - name: "add the user"
  #   replace:
  #     path: "/etc/ssh/sshd_config"
  #     regexp: '(AllowUsers.*)(\!\*)'
  #     replace: '\1 {{ user }} !*'
  #   when: user not in allowed_users