# TO GENERATE ENCRYPTED PASSWORD
# python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"

- hosts: remote-server
  become: yes
  vars:
    - user: new_demo_user
    # - password: $6$Tcbsq3KfmfVbr/BZ$sFBRNEBwCV5yn3u6e/vshL6BVkSuPDzLUgiq8annOX.TJPpqoGmuNPaqnMY9EoFnHPlefAHJBQgZ8MUILdgDT1
    - password: demo
  tasks:
    - name: Change user password
      user:
        name: "{{ user }}"
        update_password: always
        password: "{{ password | password_hash('sha512') }}"