# TO GENERATE ENCRYPTED PASSWORD
# python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"

- name: Create Remote User
  hosts: remote-server
  become: yes
  vars:
    - user: new_demo_user
    - password: admin

  tasks:
  - name: Create a login user
    user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
      groups:
        - sudo
      state: present